### ISSUE TITLE
Import modules/custom objects?

### ISSUE THREAD

**Issue by Shoti2313** [wechatjs/vdebugger#1]
Is it possible to import modules, custom objects that can be accessed in the evaluate function?

**Comment by Siubaak** [comment]
Do you mean using `import` in `vDebugger.evaluate`? No, because `vDebugger.evaluate` is used for running expressions instead of statements. If you want to access your custom objects, I think the only way is to mount them at the global this like `window`, and access from global.

Or, if you mean using `import` in `vDebugger.debug`, that's possible. [There are two ways.](https://jsbin.com/nosemexetu/edit?js,console)

**Comment by Shoti2313** [comment]
Awesome! Will try these. Thank you @Siubaak
